# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b841b08ffdf0e4f745adcf2c793b60874ad7d8fd9ffbd9005ae66ab21aa4cf3a8d17904e796c79a61880204739d267cd0f830e96fddc9fe127826fa9abd7d175

test:
  secret_key_base: cec3e61fd39399ad449f00ac960a953872a129e6886d151d3458f9c56a9c695709d05cac86d5e2896bb12619234d4de049b5dd24961c2bb10e41ce222984afe9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
